use_frameworks!

platform :ios, '8.0'

target 'CFFoundation_Example' do
  pod 'CFFoundation', :path => '../'

  target 'CFFoundation_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
